### ISSUE TITLE
Two state at the same time.

### ISSUE THREAD

**Issue by nurpais** [Cuberto/mouse-follower#11]
is it possible to enable two states at the same time?

I want to set a img and text to the cursor, the picture and text are displayed, but without the text background.

I apologize if I missed something in the documentation. Thank you!

![image](https://user-images.githubusercontent.com/25268319/187211522-925376b5-6d51-4cd0-9c6f-7b570c513e1f.png)

**Comment by Drafteed** [comment]
Hello! This is a non-standard case and requires customization via CSS.

Example: 
```scss
.mf-cursor {
    &.-video.-text {
        width: auto;
        height: auto;
        top: auto;
        left: auto;
        z-index: 10;
        transform: translate(-50%, -50%);
        padding: 20px;

        background: currentColor;
        border-radius: 50%;
    }
}
```
