### ISSUE TITLE
How to remove the cursor from responsive designs

### ISSUE THREAD

**Issue by soniasaini0075** [Cuberto/mouse-follower#14]

**Comment by Giuseppetm** [comment]
You have to manipulate `.mf-cursor` class; set the max-width to anything you like.

```css
.mf-cursor { 
  @media screen and (max-width: 769px) {
    display: none;
  }
}
```
