### ISSUE TITLE
How to change cursor background color dynamically?

### ISSUE THREAD

**Issue by dropways** [Cuberto/mouse-follower#35]
I wan to use colorful cursor not only black and white.

I have a slider color with dynamically slide color so I need to use dynamic cursor background color.

Please suggest me solution.

Thank you in advance

**Comment by Drafteed** [comment]
Use a custom CSS:

```scss
.my-cursor.-red {
    color:#ff0000;
}
```

```html
<div data-cursor="-red">Red cursor!</div>
```
